// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgfCBHC_c0yK4ka9SexF3tP-dZBLo28qc',
    appId: '1:342871949394:android:8f836cb1f958c09c9b1f8b',
    messagingSenderId: '342871949394',
    projectId: 'flutter-maps-8581a',
    storageBucket: 'flutter-maps-8581a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7GOP088UQWCWBjTy-iT6lwoCnYO_Pm8',
    appId: '1:342871949394:web:25035c88144827a89b1f8b',
    messagingSenderId: '342871949394',
    projectId: 'flutter-maps-8581a',
    authDomain: 'flutter-maps-8581a.firebaseapp.com',
    storageBucket: 'flutter-maps-8581a.firebasestorage.app',
    measurementId: 'G-Z8QNV76NHZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxmtDh7HXzqz2GLmuYRNKiPGZ0VnxTlE',
    appId: '1:342871949394:ios:fd7ccacfefc0672f9b1f8b',
    messagingSenderId: '342871949394',
    projectId: 'flutter-maps-8581a',
    storageBucket: 'flutter-maps-8581a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMaps',
  );

}